### ISSUE TITLE
Implement UI

### ISSUE THREAD

**Issue by samhstn** [dwyl/tudo#177]
Based on this mockup: https://gomockingbird.com/projects/ypx5di4/4gXVnC

- [x] #173 Set up Tachyons
- [x] #170 Add dwyl favicon
- [x] #171 Add Help Wanted image
- [x] #172 Add intro copy with links
- [x]  #188 Write intro copy
- [x] #182 Add dwyl-site colours
- [x] #189 Pagination
- [x] #176 Table of issues
![screen shot 2017-07-28 at 16 47 16](https://user-images.githubusercontent.com/15983736/28725163-8da774ea-73b4-11e7-9f47-a21083aab572.png)
